### ISSUE TITLE
Missing header files J2ObjC_source.h and J2ObjC_header.h

### ISSUE THREAD

**Issue by k06a** [goodow/j2objc#5]
I used J2ObjC 0.9.6 to convert Java source code to Objective-C. Generated source code have a lot of imports of `J2ObjC_source.h` and `J2ObjC_header.h`. But this files can not be found in this pod.

I forked this repo, updated podspec for 0.9.6 and installed it into project. But this does not helps. Where are these files?

**Comment by larrytin** [comment]
Also update [scripts/download_distribution.sh](https://github.com/goodow/j2objc/blob/master/scripts/download_distribution.sh) like commit 09e6830f627762e4384296893854e2e9475e4052.

**Comment by k06a** [comment]
@larrytin thank you! That works. I am closing issue.

Anyone who is interested in 0.9.6 can use:
```
pod 'J2ObjC', :git => 'https://github.com/actorapp/j2objc'
```
