### ISSUE TITLE
Upgrade J2ObjC cocoapods spec to 0.9.7

### ISSUE THREAD

**Issue by vnavarro** [goodow/j2objc#7]
If possible. Anyway thanks in advance!

**Comment by peterholc** [comment]
:+1:

**Comment by larrytin** [comment]
Test 0.9.7 using:
```
pod 'J2ObjC', :git => 'https://github.com/goodow/j2objc'
```

**Comment by vnavarro** [comment]
@larrytin I tested and its working, yet I need to ship J2ObjC as a depency in my own pod and for that to work I had to tweak the  J2OjC.podspec.json to use master branch. Is it possible to add v0.9.7-lib tag? If so I can create the issue.

**Comment by larrytin** [comment]
Done!

**Comment by vnavarro** [comment]
Thanks! :smile: :+1:
